### ISSUE TITLE
USER STORY: Adjust product quantity MS4

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#20]
As a **user**, I want **to be able to adjust the quantity of products in my shopping cart** so that **I can control the quantity of items I want to purchase on BookHeaven.**

## Acceptance Criteria
- Given I am a logged-in user and I have added products to my cart, When I navigate to the "My Cart" page or section, Then I should be able to view the list of products I have added along with the ability to increase or decrease the quantity for each product.
- Given I am a logged-in user and I have added products to my cart, When I increase or decrease the quantity of a product, Then the total cart price should update accordingly based on the adjusted quantities.

## Tasks:
- [x] Design and implement the frontend template for the "My Cart" page, including quantity adjustment options for each product.
- [x] Implement the logic to display the user's shopping cart on the "My Cart" page, including the quantity adjustment feature.
- [x] Design and implement the quantity adjustment interface, including buttons or input fields for increasing and decreasing quantities.
- [x] Implement the logic to update the cart's total price when product quantities are adjusted.

**Comment by Dayana-N** [comment]
completed
