### ISSUE TITLE
USER STORY: Mailchimp Newsletter MS7

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#31]
As a **user**,  I want **to sign up for newsletters on the website** so that **I can keep up with updates and deals.**

## Acceptance Criteria
- Given I am a user, When I visit the website, Then I should see a clear and accessible option to subscribe to newsletters on the homepage or footer.
- Given I am a user, When I submit the subscribe form with my email, Then I should see confirmation message.

## Tasks:
- [x] Create an account on Mailchimp website.
- [x] Copy the code for the form into the footer
- [x] Test that the form works correctly

**Comment by Dayana-N** [comment]
completed
