### ISSUE TITLE
USER STORY: Sort products by name and price

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#34]
As a **user** I want to be able to **sort the list of available products by name and price** so that I can **easily find books that match my interests**

## Acceptance Criteria:

- Given I am on the bookshop's  "All Products" page, When I navigate to a product sort dropdown menu, Then I should see a list of available sorting options to choose from.
- Given I am on the bookshop's  "All Products" page, When I select a specific sorting option from the list, Then the list of displayed products should be filtered to include only products that belong to the selected sorting category.

## Tasks:

- [x] Create a sorting dropdown menu on the "All Products" page.
- [x] Add options for sorting by name and price in the dropdown.
- [x] Create back-end logic to handle sorting products by name and price.
- [x] Implement sorting based on the user's selected sorting option.

**Comment by Dayana-N** [comment]
completed
