### ISSUE TITLE
USER STORY: Checkout functionality MS4

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#38]
As a **User** I want to be able to **complete the checkout process for my shopping cart** so that I can **purchase the items I've added to my cart**

## Acceptance Criteria:

- Given I'm on the checkout page, when I review my cart contents, then I should see a summary of items in my cart, including their names, quantities, prices, and total cost.
- Given I need to provide my delivery and billing information, when I enter this information, then I should see fields for full name, email, phone number and shipping address
- Given my order total meets or exceeds the "FREE DELIVERY" threshold, when the delivery cost is calculated, then it should be displayed as €0.

## Tasks:
- [x] Create checkout app and order models.
- [x] Create a checkout page that displays cart's content
- [x] Implement a form to collect and validate user's billing and delivery information
- [x] Implement the logic to determine the delivery cost based on the amount spent.
- [x] Implement the logic to calculate the order total.

**Comment by Dayana-N** [comment]
completed
