### ISSUE TITLE
USER STORY: All products view MS2

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#6]
As a **user** I want to be able to **view a list of all available products** in the bookshop so that I can **browse and choose books to purchase**

## Acceptance Criteria:

- Given I am on the bookshop's homepage, When I click on the "Browse All Products" link in the navigation menu, Then I should be directed to a page displaying a paginated list of all available products.

- Given I am on the "All Products" page, When I scroll down, Then I should see a list of product cards, each containing:
    The book's title
    The book's author
    The book's cover image
    The book's price
    An "Add to Cart" button
 
- Given I am on the "All Products" page, When I click on a product card, Then I should be directed to a product detail page where I can view more information about the selected product.

## Tasks:
- [x] Create a Django view for displaying all products.
- [x] Create a template for the "All Products" page to render the list of products.
- [x] Create a product model in the database with fields for title, author, cover image, price, and other relevant information.
- [x] Implement pagination for the list of products to display a reasonable number per page.
- [x] Create a "Browse All Products" link in the navigation menu that points to the "All Products" view.
- [x] Ensure proper URL routing for the "All Products" page.
- [x] Implement and style the product cards on the "All Products" page.

**Comment by Dayana-N** [comment]
pagination covered in issue #11 
Completed
