### ISSUE TITLE
USER STORY: Refine products by category

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#8]
As a **user** I want to be able to ** refine the list of available products by selecting a specific category** so that I can **easily find books that match my interests**

## Acceptance Criteria:

- Given I am on the bookshop's homepage or "All Products" page, When I navigate to a product category section or dropdown menu, Then I should see a list of available product categories to choose from.

- Given I am on the bookshop's homepage or "All Products" page, When I select a specific category from the list, Then the list of displayed products should be filtered to include only products that belong to the selected category.

- Given I am on the bookshop's homepage or "All Products" page, When I select a category that has no associated products, Then I should see a message indicating that there are no products in the selected category.

- Given I am on the bookshop's homepage or "All Products" page, When I select a category, Then I should have the option to clear the category filter and view all products again.

## Tasks:

- [x] Define the product category model in the Django project.
- [x] Populate the database with various product categories (e.g., Fiction, Non-fiction, Mystery, Science Fiction, Romance, etc.).
- [x] Add a product category field to the product model to associate each product with a category.
- [x] Update the product views to filter products based on the selected category.
- [x] Create a template for displaying the list of available product categories.
- [x] Implement a dropdown menu for selecting product categories on the homepage or "All Products" page.

**Comment by Dayana-N** [comment]
completed
