### ISSUE TITLE
USER STORY: Product's author view MS2

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/Book-Heaven-PP5#9]
As a **User** I want to be able to **view detailed information about a product's author, including their name, a short biography, and a list of books available for sale on the website** so that I can **learn more about the author and explore their other works.**

## Acceptance Criteria:

- Given I am on the bookshop's homepage or a product detail page, When I click on the name of the product's author, Then I should be directed to an "Author Profile" page.

- Given I am on the "Author Profile" page, When I view the page, Then I should see the following information about the author:

1. The author's name
2. A short biography or description of the author
3. A list of books by the author that are available for sale on the website
4. For each book in the list, display the book's title, cover image, and price

- Given I am on the "Author Profile" page, When I click on the title or image of a book by the author, Then I should be directed to the "Single Product View" page for that book, where I can view more details and potentially make a purchase.

- Given I am on the "Author Profile" page, When I click on the "Go Back" button, Then I should be directed back to the previous page (e.g., the product detail page or the homepage).

## Tasks:

- [x] Create a Django view for displaying an author's profile.
- [x] Define a model for authors in your Django project, including fields for the author's name and biography.
- [x] Update the product model to include a foreign key relationship with the author model to associate products with their respective authors.
- [x] Implement URL routing for the "Author Profile" page.
- [x] Create a template for displaying author profiles with the necessary information (name, biography, list of books).
- [x] Retrieve and display the list of books by the author on the author profile page.
- [x] Add links to navigate to the "Single Product View" for each book in the list.
- [x] Implement a "Go Back" button to allow users to navigate back to the previous page.

**Comment by Dayana-N** [comment]
completed
